cert:
    build: ./config/letsencrypt
    volumes:
        - ./persistent/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt
        - /srv/letsencrypt-webrootauth
    command: root certonly --renew-by-default -a webroot --webroot-path /srv/letsencrypt-webrootauth --text --agree-tos --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory --email ##EMAIL## -d ##DOMAIN## -d www.##DOMAIN##